version: '2.0'
services:
  tomcat:
    image: elogistik-web-img
    container_name: elogistik-web-svc
    build:
      context: ./
      dockerfile: tomcat.dockerfile
      args:
        - http_proxy="http://iqbalkhowarizmi:20365745@cache.itb.ac.id:8080/"
        - https_proxy="http://iqbalkhowarizmi:20365745@cache.itb.ac.id:8080/"
        - no_proxy
    ports:
      - "9000:8080"
    networks:
      - elogistik-net
networks:
    elogistik-net:
        external:
            name: elogistik-net