version: '2'

services:
  entity-service:
    image: elogistik-entity-img
    container_name: elogistik-entity-svc
    build: 
      context: ./api
      args:
        - http_proxy="http://iqbalkhowarizmi:20365745@cache.itb.ac.id:8080/"
        - https_proxy="http://iqbalkhowarizmi:20365745@cache.itb.ac.id:8080/"
        - no_proxy
    ports:
      - 3000:3000
    networks:
      - elogistik-net
networks:
    elogistik-net:
        external:
            name: elogistik-net
