version: '2.0'
services:
  task-worker:
    image: elogistik-worker-img
    container_name: elogistik-worker-svc
    build:
      context: ./
      dockerfile: worker.dockerfile
    networks:
      - elogistik-net
networks:
    elogistik-net:
        external:
            name: elogistik-net
