version: '2.0'
#services:
#  task-service:
#    image: elogistik-task-img
#    container_name: elogistik-task-svc
#    build:
#      context: ./
#      dockerfile: camunda.dockerfile
#    ports:
#      - "9001:8080"
services:
  task-worker:
    image: elogistik-worker-img
    container_name: elogistik-worker-svc
    build:
      context: ./
      dockerfile: worker.dockerfile
      args:
        - http_proxy
        - https_proxy
    networks:
      - elogistik-net
networks:
    elogistik-net:
        external:
            name: elogistik-net
