version: '2.0'
services:
  nginx:
    image: nginx:alpine
    container_name: task-service_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./SOAP:/home/src/SOAP:ro
    links:
      - php
  php:
    image: task-service
    container_name: task-service_php
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - ./SOAP:/home/src/SOAP:ro
    ports:
      - "9000:9000"
volumes:
  SOAP:
    driver: local
