version: '2.0'
services:
  task-worker:
    image: elogistik-worker-img
    container_name: elogistik-worker-svc
    build:
      context: ./
      dockerfile: worker.dockerfile
      args:
        - http_proxy="http://iqbalkhowarizmi:20365745@cache.itb.ac.id:8080/"
        - https_proxy="http://iqbalkhowarizmi:20365745@cache.itb.ac.id:8080/"
        - no_proxy
    networks:
      - elogistik-net
networks:
    elogistik-net:
        external:
            name: elogistik-net
